### ISSUE TITLE
This plugin is not effective when enabled on IntelliJ IDEA 2024.1.5 (Ultimate Edition)

### ISSUE THREAD

**Issue by bingfenglai** [xdev-software/intellij-plugin-save-actions#136]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/xdev-software/intellij-plugin-save-actions/releases/latest)
- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/intellij-plugin-save-actions/issues) or [closed](https://github.com/xdev-software/intellij-plugin-save-actions/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

1.2.3

### Steps to reproduce the bug

This plugin is not effective when enabled on IntelliJ IDEA 2024.1.5 (Ultimate Edition)

### Additional information

<img width="785" alt="image" src="https://github.com/user-attachments/assets/1e9e99f7-a0a5-4d0e-ad9e-19282a15db3d">

**Comment by AB-xdev** [comment]
> This plugin is not effective when enabled on IntelliJ IDEA 2024.1.5

What exactly do you mean with "effective"?
Does something not work? If so please showcase/describe in more detail what is broken.

I was working with the plugin on IDEA 2024.1.6 for the past weeks and didn't encounter any problems.

**Comment by bingfenglai** [comment]
I configured as shown in the figure, but when saving the code, I found that the plugin was not working, the code format was not adjusted, and the imported packages that were not referenced were not deleted.
The use of command+s did not take effect

**Comment by AB-xdev** [comment]
Tried to reproduce the problem but still couldn't in IDEA 2024.1.6.

Could you provide the following additional information:
* ``saveactions_settings.xml`` (contains all settings) from the ``.idea`` folder of your project
* When you open the logs (``Help -> Open Log in Editor / Show logs in explorer``) are there any exceptions that are related to the plugin? (easiest way is to search for ``software.xdev.saveactions``)
* Does this only happen in one project? You can also checkout one of our java projects that uses the plugin for comparison, e.g. https://github.com/xdev-software/chartjs-java-model

**Comment by AB-xdev** [comment]
Closing due to lack of feedback
