### ISSUE TITLE
Changelog for 1.4.0 missing

### ISSUE THREAD

**Issue by fishermans** [xdev-software/intellij-plugin-save-actions#186]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/intellij-plugin-save-actions/issues) or [closed](https://github.com/xdev-software/intellij-plugin-save-actions/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

Change log ends with v1.3.1. Could you please update the change log for v1.4.0?

THX

**Comment by AB-xdev** [comment]
Oh it looks like this was lost while merging the changes from 2024.3

Anyway thank you for the hint I added it now :)
