### ISSUE TITLE
Comment alignment when saved

### ISSUE THREAD

**Issue by cycle2zhou** [xdev-software/intellij-plugin-save-actions#86]
When saving, java document comments are automatically aligned, parameter comments that do not exist are automatically added, and redundant ones are automatically deleted

**Comment by AB-xdev** [comment]
> When saving, java document comments are automatically aligned, parameter comments that do not exist are automatically added, and redundant ones are automatically deleted

Yeah depending on how you configured the plugin that is what it does. 
What exactly now is the issue with that?

**Comment by cycle2zhou** [comment]
<img width="518" alt="image" src="https://github.com/xdev-software/intellij-plugin-save-actions/assets/33155330/4c915e2c-5517-4603-9db9-dad4a49d0246">


What I'm referring to in the figure is that the actual parameters on the Java Doc and method are automatically consistent

**Comment by AB-xdev** [comment]
> What I'm referring to in the figure is that the actual parameters on the Java Doc and method are automatically consistent

Okay I still can't quite follow what that has to do with the plugin as I can't find such an option in the plugin settings...

**Comment by AB-xdev** [comment]
There is a JavaDoc section inside ``Settings > Editor > Code Style > Java``:

![g](https://github.com/xdev-software/intellij-plugin-save-actions/assets/45384811/5d154f3c-614b-4369-8dfe-90df4f1ecbcc)

Are you referring to this?
Because this is a built-in IDE option and not part of the plugin..

**Comment by cycle2zhou** [comment]
When a parameter in a method is missing in a Java doc, the @ param annotation will not be automatically added. I hope that the Save action plugin can automatically add the missing @ param in the Java doc or delete the @ param corresponding to the parameter that does not exist in the method when saving

**Comment by cycle2zhou** [comment]
When a parameter in a method is missing in a Java doc, the @ param annotation will not be automatically added. I hope that the Save action plugin can automatically add the missing @ param in the Java doc or delete the @ param corresponding to the parameter that does not exist in the method when saving

**Comment by cycle2zhou** [comment]
When a parameter in a method is missing in a Java doc, the @ param annotation will not be automatically added. I hope that the Save action plugin can automatically add the missing @ param in the Java doc or delete the @ param corresponding to the parameter that does not exist in the method when saving

**Comment by AB-xdev** [comment]
> I hope that the Save action plugin can automatically add the missing @ param in the Java doc or delete the @ param corresponding to the parameter that does not exist in the method when saving

1. Is this a feature request?
  * If so please describe this somewhere inside the issue, that you want functionality XY!
  * The plugin is in maintenance mode; We usually don't do feature requests:<br/>![g](https://github.com/xdev-software/intellij-plugin-save-actions/assets/45384811/c20236ab-ccf3-4e80-a46b-07eaf9b7b50b)
2. The plugin usually just calls IntelliJ inspections. I couldn't find any inspection for your request so I don't think it can be implemented easily; However feel free to send a PR if you want to
3. Not sure if this helps but [Checkstyle has some JavaDoc configurations options](https://checkstyle.org/checks/javadoc/index.html). Maybe this is what you want...

**Comment by cycle2zhou** [comment]
Yes, this is a new function request, if the current project is only in the maintenance phase, then there is no way, thank you for your answer
